#!/bin/bash
#chkconfig:2345 85 15
#
# @author zhangqiang<komazhang@foxmail.com>
# @date   2015.06.30 17:30:28

NGINX_EXEC=''
NGINX_PID=''
if [ "$1" == "start" ];then
    $NGINX_EXEC
    if [ $? -eq 0 ];then
        echo " nginx start...                     [OK] "
    else
        echo " nginx start...                     [Faild] "
        exit 1
    fi
elif [ "$1" == "stop" ];then
    kill -QUIT `cat ${NGINX_PID}`
    if [ $? -eq 0 ];then
        echo " nginx stop...                     [OK] "
    else
        echo " nginx stop...                     [Faild] "
        exit 1
    fi
elif [ "$1" == "restart" ];then
    kill -HUP `cat ${NGINX_PID}`
    if [ $? -eq 0 ];then
        echo " nginx restart...                     [OK] "
    else
        echo " nginx restart...                     [Faild] "
        exit 1
    fi
else
    echo " command args not defined! "
    exit 1
fi
exit 0
